services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: chatroom # 数据库名称
      POSTGRES_USER: gopher # 用户名
      POSTGRES_PASSWORD: 1900271083 # 密码
    command: ["postgres", "-c", "max_connections=1000"]
    ports:
      - "5432:5432" # 映射主机端口到容器
    volumes:
      - /var/lib/postgresql
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
